
#Modern Forwarding Settings
[modernForwarding]
	forwardingSecret = ""

[commandWrapping]
	#List of argument types that are not vanilla but are integrated into the server (found in the Vanilla registry)
	moddedArgumentTypes = ["livingthings:sampler_types"]

